### ISSUE TITLE
夏イベント用機能拡張

### ISSUE THREAD

**Issue by Xeltica** [XelticaMC/X-Core#28]
* 時間計測システム
* Ranking API

## 時間計測
2つの感圧板を登録
`/counter register <name>` を実行後に2つの感圧板を順番にクリックするタイプ

登録された感圧板をプレイヤーが踏むと作動するように

### データ定義

以下の構造を `counter.yml` に記録する

```yaml
"カウンター名: string":
  name: "カウンター名: string"
  location1: "始点: org.bukkit.Location"
  location2: "終点: org.bukkit.Location"
  isDaily: "1日1回チャレンジかどうか: boolean"
  rankingId: "連携ランキングID: UUID | null"
```

### イベント

カウント開始時と終了時にイベントを発行。それぞれ `PlayerCounterStart` `PlayerCounterFinish` イベントで購読可能。

### ランキング連携

登録した時間計測をランキングと連携させる。具体的には上記のイベントで実装する。
`/counter bind <playerType> <rankingName>`

- playerType
  - all - 全てのプレイヤー
  - java - Javaプレイヤー
  - uwp - Windows 10 プレイヤー
  - phone - iOS, iPadOS, Android, Nintendo Switch などのプレイヤー
  - bedrock - 統合版プレイヤー

### 登録

文字列IDと数値のペアからなるレコードを記録し、ランキングとして管理する機能
`/ranking create <name> <displayName>`

コマンドでランキングへの登録・削除ができる他、X-Core Ranking APIを用いてプラグインから制御することもできる。

### データ構造

以下の構造を `ranking.yml` に記録する

```yml
"ランキング名: string":
  displayName: "表示名: string"
  records: # 配列
    "ID: string": "スコア: int"
```

### API

```java
// Ranking API の利用
RankingStore rankingApi = RankingStore.getInstance();

// 今回IDとして扱うプレイヤーID
OfflinePlayer player = Bukkit.getOfflinePlayer("Xeltica");
String id = player.getUniqueId().toString();

// ランキング作成
Ranking ranking = rankingApi.create("id", "display name");

// レコード追加
ranking.add(id, 50);

// レコード削除
ranking.remove(id);

// ランキングIDからランキング取得
Ranking ranking2 = rankingApi.get("name");

// レコードの値を取得
double value = ranking2.get(id);
```

## ランキング表示

ランキングの内容をホログラム表示するシステム

[Holographic Displays](https://dev.bukkit.org/projects/holographic-displays) プラグインが提供するAPIを用いる

**設置** `/ranking hologram create <name> <rankingName>`
**撤去** `/ranking hologram delete <name>`
**文字を隠す** `/ranking hologram censor <name>`
**文字隠しを解除** `/ranking hologram uncensor <name>`
